name: Auto Format Google Style

on:
  push:
    branches: [ preprod ]
  pull_request:
    branches: [ preprod ]

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21' # google-java-format requiert désormais JDK 21+ pour tourner

    - name: Run Google Java Format
      uses: axel-op/googlejavaformat-action@v4
      with:
        args: "--replace"
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style: apply Google Java Format"

